### PR TITLE
Fix crashes in XMPPvCardTempEmail and XMPPvCardTempTel initialize

### LINKED ISSUE #1050: XMPPvCardTempEmail exits process on +initialize()
Hi,

we're dealing with vCards right now. The XMPPvCardTempEmail class is broken on XCode 9.2 with iphone 5s (or newer models). This basic XCTest fails:

```
import XCTest  
import XMPPFramework

class XMPPvCardTempEmailTest: XCTestCase { 
  
    func testXMPPvCardEmail() {  
        _ = XMPPvCardTempEmail(name: "Hello", numberValue: 1)  
    }  
  
} 
```

Error Message: 
```
2018-04-11 15:04:54.487509+0200 Messenger[96373:4956473] Adding instance variables to XMPPvCardTempEmail is not currently supported!
```

The failing check (after debugging):

```
size_t superSize = class_getInstanceSize([NSXMLElement class]); //size is 24
	size_t ourSize   = class_getInstanceSize([XMPPvCardTempEmail class]); //size is 32
	
	if (superSize != ourSize)
```

We think it's a 64 bit issue, but didn't have a readily available 32 bit setup, so not 100 % sure.

### PR DESCRIPTION
**Pull request by beribas**
Fixes #1050 and #1118.

Setter methods in `XMPPcVardTempEmail` and `XMPPcVardTempTel` had typing mistakes. Must have been happened sometime during 3.7 to 4.0 transition. 
These types do not allow adding properties, that's why the allocated size is compared to the size of `NSXMLElement` in `initialize`. 

```
+ (void)initialize {
        // .....
	size_t superSize = class_getInstanceSize([NSXMLElement class]);
	size_t ourSize   = class_getInstanceSize([XMPPvCardTempEmail class]);
	
	if (superSize != ourSize)
	{
		XMPPLogError(@"Adding instance variables to XMPPvCardTempEmail is not currently supported!");
		
		[DDLog flushLog];
		exit(15);
	}
}
```

Every added property has to have matching get and set overwrites, otherwise ObjC will allocate memory for the property and the size check will fail.
The linked issue describe that behavior.

I also added missing implementation for `TEL` and few tests for `XMPPvCardTemp`.

### CODE REVIEW

File: Xcode/Testing-Swift/XMPPvCardTempTests.swift [hunk 1]
```diff
@@ -0,0 +1,92 @@
+//
+//  XMPPvCardTempTests.swift
+//  XMPPFrameworkSwiftTests
+//
+//  Created by Oleg Langer on 07.04.20.
+//
+
+import XCTest
+import XMPPFramework
+
```
Comment (chrisballinger) [inline Xcode/Testing-Swift/XMPPvCardTempTests.swift:10]: `import KissXML`

File: Xcode/Testing-Swift/XMPPvCardTempTests.swift [hunk 2]
```diff
@@ -0,0 +1,92 @@
...
+                <USERID>q_dekstop@example.com</USERID>
+            </EMAIL>
+            <TEL>
+                <WORK/>
+                <VOICE/>
+                <NUMBER>303-308-3282</NUMBER>
+            </TEL>
+        </vCard>
+        """
+        let element = try! DDXMLElement(xmlString: xmlString)
```
Comment (chrisballinger) [inline Xcode/Testing-Swift/XMPPvCardTempTests.swift:30]: Please use `XMLElement`

**Comment by beribas** [comment]
O yes, sure, didn't know about the `XMLElement` alias.

File: Xcode/Testing-Swift/XMPPvCardTempTests.swift (hunk 1 above)
Comment (beribas) [reply Xcode/Testing-Swift/XMPPvCardTempTests.swift:10]: Seems like I don't have to import anything at all.

Comment (chrisballinger) [reply Xcode/Testing-Swift/XMPPvCardTempTests.swift:9]: Ah yeah, it's probably implicitly re-exported by XMPPFramework.

Comment (chrisballinger) [reply Xcode/Testing-Swift/XMPPvCardTempTests.swift:9]: Oh, hm that's weird that you don't even need to import XMPPFramework.

**Comment by chrisballinger** [comment]
Awesome, thank you!

File: Xcode/Testing-Swift/XMPPvCardTempTests.swift (hunk 1 above)
Comment (beribas) [reply Xcode/Testing-Swift/XMPPvCardTempTests.swift:9]: Yes, I also don't really understand why. :)
